# Generated by Django 5.2.2 on 2025-06-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_customuser_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('visitor', 'Посетитель'), ('staff', 'Сотрудник')], default='visitor', max_length=10),
        ),
    ]
