# Generated by Django 5.2.2 on 2025-06-20 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отдела')),
                ('description', models.TextField(verbose_name='Описание отдела')),
                ('employees', models.TextField(verbose_name='Сотрудники отдела (через запятую)')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Время работы отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('visit_purpose', models.CharField(choices=[('credit', 'Кредит'), ('mortgage', 'Ипотека'), ('consultation', 'Консультация'), ('other', 'Другое')], max_length=20, verbose_name='Цель визита')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, который записался на встречу (если авторизован)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись на встречу',
                'verbose_name_plural': 'Записи на встречу',
                'ordering': ['-created_at'],
            },
        ),
    ]
